# Generated by Django 4.2.5 on 2023-10-01 05:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hr", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidate",
            name="name",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="name",
        ),
        migrations.AlterField(
            model_name="candidate",
            name="id",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="employee",
            name="id",
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
