# Generated by Django 4.2.5 on 2023-10-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_remove_employee_keywords_remove_employee_resume_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='x',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='y',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='x',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='y',
            field=models.IntegerField(),
        ),
    ]
